In [3]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football.db")

players=pd.read_csv("player.csv")
#팀 테이블 만들기
teams = pd.DataFrame({
    "team": ["맨유", "토트넘", "리버풀", "맨시티"],
    "possession": [53.1, 50.8, 58.4, 61.2]
})

teams.to_sql("teams", conn, if_exists="replace", index=False)

4

In [4]:
query = """
SELECT *
FROM teams;
"""

pd.read_sql_query(query, conn)

  team  possession
0   맨유        53.1
1  토트넘        50.8
2  리버풀        58.4
3  맨시티        61.2

In [8]:
#플레이어 테이블 만들기
player=pd.DataFrame({
    "player":["세슈코","음뵈모","브루노 페르난데스","마테우스 쿠냐","마커스 래시포드"],
    "team":["맨유","맨유","맨유","맨유","맨유"]
})

player.to_sql("player", conn, if_exists="replace", index=False)

5

In [9]:
query = """
SELECT *
FROM player;
"""

pd.read_sql_query(query, conn)

      player team
0        세슈코   맨유
1        음뵈모   맨유
2  브루노 페르난데스   맨유
3    마테우스 쿠냐   맨유
4   마커스 래시포드   맨유

In [11]:
#팀 테이블 만들기
teams = pd.DataFrame({
    "team": ["맨유", "토트넘", "리버풀", "맨시티"],
    "possession": [53.1, 50.8, 58.4, 61.2]
})

teams.to_sql("teams", conn, if_exists="replace", index=False)

4

In [12]:
query = """
SELECT *
FROM teams;
"""

pd.read_sql_query(query, conn)

  team  possession
0   맨유        53.1
1  토트넘        50.8
2  리버풀        58.4
3  맨시티        61.2

In [13]:
#1
query = """
SELECT team
FROM player;
"""

pd.read_sql_query(query, conn)

  team
0   맨유
1   맨유
2   맨유
3   맨유
4   맨유

In [14]:
#2
query = """
SELECT team
FROM teams;
"""

pd.read_sql_query(query, conn)

  team
0   맨유
1  토트넘
2  리버풀
3  맨시티

In [19]:
#3
query = """
SELECT DISTINCT team
FROM player
"""

pd.read_sql_query(query, conn)

  team
0   맨유

In [20]:
player = pd.DataFrame({
    "player": ["세슈코", "음뵈모", "브루노 페르난데스", "마테우스 쿠냐", "마커스 래시포드"],
    "team": ["맨유", "맨유", "맨유", "맨유", "맨유"],
    "position": ["FW", "FW", "MF", "FW", "FW"],
    "goals": [16, 13, 11, 8, 6],
    "minutes": [2800, 2600, 3000, 2200, 1800]
})

player.to_sql("player", conn, if_exists="replace", index=False)

player

      player team position  goals  minutes
0        세슈코   맨유       FW     16     2800
1        음뵈모   맨유       FW     13     2600
2  브루노 페르난데스   맨유       MF     11     3000
3    마테우스 쿠냐   맨유       FW      8     2200
4   마커스 래시포드   맨유       FW      6     1800

In [21]:
#1
query = """
SELECT player, goals,
    CASE
        WHEN goals >=15 THEN '고득점'
        WHEN goals >=10 THEN '중간'
        ELSE '낮음'
    END AS goal_level
FROM player;
"""

pd.read_sql_query(query, conn)

      player  goals goal_level
0        세슈코     16        고득점
1        음뵈모     13         중간
2  브루노 페르난데스     11         중간
3    마테우스 쿠냐      8         낮음
4   마커스 래시포드      6         낮음

In [22]:
#2
query = """
SELECT player, minutes,
    CASE
        WHEN minutes >=2700 THEN '주전'
        WHEN minutes >=2300 THEN '로테이션'
        ELSE '제한적 출전'
    END AS play_role
FROM player;
"""

pd.read_sql_query(query, conn)

      player  minutes play_role
0        세슈코     2800        주전
1        음뵈모     2600      로테이션
2  브루노 페르난데스     3000        주전
3    마테우스 쿠냐     2200    제한적 출전
4   마커스 래시포드     1800    제한적 출전

In [24]:
#3
query = """
SELECT player, position,
    CASE
        WHEN position ="FW" THEN '공격수'
        WHEN position ="MF" THEN '미드필더'
        WHEN position = 'DF' THEN '수비'
        ELSE '골키퍼'
    END AS player_position
FROM player;
"""

pd.read_sql_query(query, conn)

      player position player_position
0        세슈코       FW             공격수
1        음뵈모       FW             공격수
2  브루노 페르난데스       MF            미드필더
3    마테우스 쿠냐       FW             공격수
4   마커스 래시포드       FW             공격수

In [27]:
#1
query = """
SELECT player.player, player.team, teams.possession
FROM player
INNER JOIN teams
ON player.team=teams.team
"""

pd.read_sql_query(query, conn)

      player team  possession
0        세슈코   맨유        53.1
1        음뵈모   맨유        53.1
2  브루노 페르난데스   맨유        53.1
3    마테우스 쿠냐   맨유        53.1
4   마커스 래시포드   맨유        53.1

In [28]:
#2
query = """
SELECT player.player, player.goals, teams.possession
FROM player
INNER JOIN teams
ON player.team=teams.team
"""

pd.read_sql_query(query, conn)

      player  goals  possession
0        세슈코     16        53.1
1        음뵈모     13        53.1
2  브루노 페르난데스     11        53.1
3    마테우스 쿠냐      8        53.1
4   마커스 래시포드      6        53.1

In [31]:
#3
query = """
SELECT player.player, player.position, player.minutes, teams.possession
FROM player
INNER JOIN teams
ON player.team=teams.team
"""

pd.read_sql_query(query, conn)

      player position  minutes  possession
0        세슈코       FW     2800        53.1
1        음뵈모       FW     2600        53.1
2  브루노 페르난데스       MF     3000        53.1
3    마테우스 쿠냐       FW     2200        53.1
4   마커스 래시포드       FW     1800        53.1

In [4]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("football.db")

player = pd.DataFrame({
    "player": ["세슈코", "음뵈모", "브루노 페르난데스", "마테우스 쿠냐", "마커스 래시포드"],
    "team": ["맨유", "맨유", "맨유", "맨유", "맨유"],
    "position": ["FW", "FW", "MF", "FW", "FW"],
    "goals": [16, 13, 11, 8, 6],
    "minutes": [2800, 2600, 3000, 2200, 1800]
})

extra_player = pd.DataFrame({
    "player": ["손흥민"],
    "team": ["LAFC"],
    "position": ["FW"],
    "goals": [12],
    "minutes": [2500]
})

player = pd.concat(
    [player, extra_player],
    ignore_index=True
)

player.to_sql("player", conn, if_exists="replace", index=False)

6

In [5]:
teams = pd.DataFrame({
    "team": ["맨유", "토트넘", "리버풀", "맨시티"],
    "possession": [53.1, 50.8, 58.4, 61.2]
})

teams.to_sql("teams", conn, if_exists="replace", index=False)

4

In [7]:
#1
query = """
SELECT player.player, player.team, teams.possession
FROM player
LEFT JOIN teams
ON player.team=teams.team
"""

pd.read_sql_query(query, conn)

      player  team  possession
0        세슈코    맨유        53.1
1        음뵈모    맨유        53.1
2  브루노 페르난데스    맨유        53.1
3    마테우스 쿠냐    맨유        53.1
4   마커스 래시포드    맨유        53.1
5        손흥민  LAFC         NaN

In [13]:
#2 선수 데이터에는 있는데 팀 데이터와 매칭되지 않는 선수는 누구인가?
query = """
SELECT player.player, player.team, teams.possession
FROM player
LEFT JOIN teams
ON player.team=teams.team
WHERE teams.possession IS NULL
"""

pd.read_sql_query(query, conn)

  player  team possession
0    손흥민  LAFC       None

In [15]:
#3 LEFT JOIN은 분석 대상을 잃지 않으면서 데이터 누락이나 매칭 오류까지 발견할 수 있게 해준다.
query = """
SELECT player.player, player.position, player.goals, teams.possession
FROM player
LEFT JOIN teams
ON player.team=teams.team
"""

pd.read_sql_query(query, conn)

#왜 손흥민의 possesion 값은 NULL로 나오는가?
#teams테이블에는 team, possession 이 둘의 칼럼이 존재하는데
#player테이블에 손흥민 선수의 team 칼럼은 LAFC로 teams 테이블에는 없는 팀명이 있다.
#INNER JOIN을 사용하면 두 테이블에서 일차하는 팀만 조회되기 때문에 손흥민 선수의 행이 결과에서 제외된다.
#반면 LEFT JOIN을 사용하게되면 손흥민 선수의 행은 그대로 남아있지만 teams 테이블에 LAFC에 대한 정보가 없어 손흥민 선수의 possession값은 NULL값이 된다.
# *NULL은 0값이 아니다*
#INNER JOIN과 LEFT JOIN의 차이는 INNER JOIN은 두 테이블을 합치게 되면 두 테이블의 JOIN 조건이 일치하지 않는 행을 결과에서 제외하는 지만,
#lEFT JOIN은 두 테이블을 합치게 될때 왼쪽 테이블의 정보는 유지하면서 오른쪽 테이블의 정보가 없을때 NULL값으로 처리된다.
#INNER JOIN은 서로 정상적으로 연결되는 데이터만 보고싶을때 유용하다는 장점이 있지만,
#LEFT JOIN은 왼쪽 테이블의 분석대상을 유지하면서, 오른쪽 테이블에서 연결되지 않는 정보는 NULL로 확인할 수 있다.

      player position  goals  possession
0        세슈코       FW     16        53.1
1        음뵈모       FW     13        53.1
2  브루노 페르난데스       MF     11        53.1
3    마테우스 쿠냐       FW      8        53.1
4   마커스 래시포드       FW      6        53.1
5        손흥민       FW     12         NaN

In [20]:
#1 중복검사
query = """
SELECT player, team, COUNT(*) AS count
FROM player
GROUP BY player, team
HAVING COUNT(*) > 1;
"""

pd.read_sql_query(query, conn)
#이 조건을 만족하는 데이터가 없다. player와 team 조합이 2회 이상 반복된 행이 확인되지 않았다. 따라서 현재 데이터에서는 선수-팀 기준의 
#중복 데이터가 없는 것으로 확인됐다.

Empty DataFrame
Columns: [player, team, count]
Index: []

In [21]:
#2 결측값 검사
query = """
SELECT *
FROM player
WHERE player IS NULL
   OR team IS NULL
   OR position IS NULL
   OR goals IS NULL
   OR minutes IS NULL;
"""

pd.read_sql_query(query, conn)
#따라서 현재 데이터에서는 선수-팀 기준의 결측 데이터가 없는 것으로 확인됐다.

Empty DataFrame
Columns: [player, team, position, goals, minutes]
Index: []

In [22]:
#3 매칭 검사
query = """
SELECT DISTINCT player.team
FROM player
LEFT JOIN teams
ON player.team= teams.team
WHERE teams.team IS NULL;
"""

pd.read_sql_query(query, conn)
#player테이블의 팀들을 기준으로 teams와 연결하고, teams 쪽에서 매칭되지 않는 행만 남긴뒤, 중복없이 팀명만 보여준다.
#팀명 매칭을 확인한 결과 player테이블의 LAFC가 teams테이블과 연결되지 않았다. 이는 팀 데이터 누락 또는 팀명 표기 불일치 등의 가능성이 있으므로
#분석 전에 원인을 확인해야 한다.

##위의 활동들은 위 데이터들을 분석에 사용해도 상태인지에 대해 검사하는 것으로 첫번째는 중복 데이터 찾기, 결측값 데이터 찾기, 팀이름이 정상적으로
#연결되는지를 확인했다.
#1. 중복 검사에서 중복 선수 행 확인결과 player와 team의 조합으로 중복된 데이터가 검측되지 않았다.
#2. 결측값 검사에서 NULL값 확인 결과 결측값 결과가 검측되지 않았다.
#3. 팀명 매칭에서 결과값이 LAFC가 나왔다.
#결과: 품질 겸사 결과 중복 데이터와 결측값은 확인되지 않았다.
#하지만 player테이블의 teams 테이블과 정상적으로 매칭되지 않았기 때문에,
#팀정보를 사용하는 분석을 진행하기 전 LAFC 데이터의 누락 또는 팀명 표기 문제를 먼저 확인해야 한다.

   team
0  LAFC

In [1]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football.db")

player=pd.read_csv("player.csv")

player = pd.DataFrame({
    "player": ["세슈코", "음뵈모", "브루노 페르난데스", "마테우스 쿠냐", "마커스 래시포드", "손흥민"],
    "team": ["맨유", "맨유", "맨유", "맨유", "맨유", "LAFC"],
    "position": ["FW", "FW", "MF", "FW", "FW", "FW"],
    "goals": [16, 13, 11, 8, 6, 12],
    "assists": [5, 9, 14, 7, 6, 8],
    "passes": [760, 1030, 2010, 980, 870, 1100],
    "shots": [79, 67, 73, 52, 48, 65],
    "minutes": [2800, 2600, 3000, 2200, 1800, 2500]
})

player.to_sql("player", conn, if_exists="replace", index=False)

6

In [2]:
teams = pd.DataFrame({
    "team": ["맨유", "토트넘", "리버풀", "맨시티", "LAFC"],
    "possession": [53.1, 50.8, 58.4, 61.2, 52.4]
})

teams.to_sql("teams", conn, if_exists="replace", index=False)

5

In [5]:
#2
query = 
""" SELECT player.player, player.team, player.position, player.goals, player.assists, player.passes, player.shots,player.minutes, teams.possession 
FROM player
LEFT JOIN teams
ON player.team=teams.team """

pd.read_sql_query(query, conn)

,player,team,position,goals,assists,passes,shots,minutes,possession
0,세슈코,맨유,FW,16,5,760,79,2800,53.1
1,음뵈모,맨유,FW,13,9,1030,67,2600,53.1
2,브루노 페르난데스,맨유,MF,11,14,2010,73,3000,53.1
3,마테우스 쿠냐,맨유,FW,8,7,980,52,2200,53.1
4,마커스 래시포드,맨유,FW,6,6,870,48,1800,53.1
5,손흥민,LAFC,FW,12,8,1100,65,2500,52.4

In [7]:
#3
query = """
SELECT player.player, player.team, player.position, player.goals, player.assists, player.passes, player.shots,player.minutes, teams.possession,
        CASE
            WHEN player.goals>=15 THEN '주 득점원'
            WHEN player.goals>=10 THEN '득점 기여'
            ELSE '낮은 득점 기여'
        END AS goal_level,

        CASE
            WHEN player.minutes>=2700 THEN '핵심 주전'
            WHEN player.minutes>=2300 THEN '주요 로테이션'
            ELSE '제한적 출전'
        END AS playing_role
FROM player
LEFT JOIN teams
ON player.team=teams.team
"""

pd.read_sql_query(query, conn)

#1. 선수별 득점 수준과 출전 역할을 비교했을때, 주 득점원과 핵심 주전은 누구이며 두 분류는 항상 일치하는가?
#2. 팀 점유율이 높은 팀의 선수들이 더 많은 패스에 관여하는가?
#3. 팀 점유율차이에 따라 선수들의 평균 슈팅수나 패스 수에도 차이가 나타나는가?

,player,team,position,goals,assists,passes,shots,minutes,possession,goal_level,playing_role
0,세슈코,맨유,FW,16,5,760,79,2800,53.1,주 득점원,핵심 주전
1,음뵈모,맨유,FW,13,9,1030,67,2600,53.1,득점 기여,주요 로테이션
2,브루노 페르난데스,맨유,MF,11,14,2010,73,3000,53.1,득점 기여,핵심 주전
3,마테우스 쿠냐,맨유,FW,8,7,980,52,2200,53.1,낮은 득점 기여,제한적 출전
4,마커스 래시포드,맨유,FW,6,6,870,48,1800,53.1,낮은 득점 기여,제한적 출전
5,손흥민,LAFC,FW,12,8,1100,65,2500,52.4,득점 기여,주요 로테이션

In [8]:
final_df = pd.read_sql_query(query, conn)

In [9]:
final_df.isnull().sum()#결측지 확인

player          0
team            0
position        0
goals           0
assists         0
passes          0
shots           0
minutes         0
possession      0
goal_level      0
playing_role    0
dtype: int64

In [10]:
final_df.to_csv(
    "week11_joined_player_team.csv",
    index=False,
    encoding="utf-8-sig"
)