In [4]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football.db")

players=pd.read_csv("player.csv")

query = """
SELECT COUNT(*)
FROM players;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0         5

In [5]:
query = """
SELECT COUNT(*)
FROM players
WHERE goals>=10;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0         2

In [6]:
query = """
SELECT SUM(goals)
FROM players;
"""

pd.read_sql_query(query, conn)

   SUM(goals)
0          41

In [7]:
query = """
SELECT SUM(assists)
FROM players;
"""

pd.read_sql_query(query, conn)

   SUM(assists)
0            21

In [8]:
query = """
SELECT AVG(goals)
FROM players;
"""

pd.read_sql_query(query, conn)

   AVG(goals)
0         8.2

In [9]:
query = """
SELECT AVG(assists)
FROM players;
"""

pd.read_sql_query(query, conn)

   AVG(assists)
0           4.2

In [10]:
query = """
SELECT MIN(goals)
FROM players;
"""

pd.read_sql_query(query, conn)

   MIN(goals)
0           2

In [11]:
query = """
SELECT MIN(assists)
FROM players;
"""

pd.read_sql_query(query, conn)

   MIN(assists)
0             1

In [12]:
query = """
SELECT MAX(goals)
FROM players;
"""

pd.read_sql_query(query, conn)

   MAX(goals)
0          15

In [13]:
query = """
SELECT MAX(assists)
FROM players;
"""

pd.read_sql_query(query, conn)

   MAX(assists)
0             9

In [14]:
#1
query = """
SELECT COUNT(*)
FROM players;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0         5

In [15]:
#2
query = """
SELECT SUM(goals)
FROM players;
"""

pd.read_sql_query(query, conn)

   SUM(goals)
0          41

In [18]:
#3
query = """
SELECT AVG(assists)
FROM players;
"""

pd.read_sql_query(query, conn)

   AVG(assists)
0           4.2

In [17]:
#4
query = """
SELECT MIN(goals)
FROM players;
"""

pd.read_sql_query(query, conn)

   MIN(goals)
0           2

In [19]:
#5
query = """
SELECT MAX(assists)
FROM players;
"""

pd.read_sql_query(query, conn)

   MAX(assists)
0             9

In [20]:
#6
query = """
SELECT COUNT(*)
FROM players
WHERE goals>=10
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0         2

In [21]:
#7
query = """
SELECT SUM(goals)
FROM players
WHERE team="토트넘"
"""

pd.read_sql_query(query, conn)

   SUM(goals)
0          15

In [22]:
#8
query = """
SELECT AVG(assists)
FROM players
WHERE team="토트넘"
"""

pd.read_sql_query(query, conn)

   AVG(assists)
0           9.0

In [23]:
#9
query = """
SELECT MAX(goals)
FROM players
WHERE goals>=5
"""

pd.read_sql_query(query, conn)

   MAX(goals)
0          15

In [24]:
#10
query = """
SELECT AVG(goals)
FROM players
WHERE team="토트넘"
"""

pd.read_sql_query(query, conn)

   AVG(goals)
0        15.0

In [1]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football.db")

players=pd.read_csv("player.csv")

query = """
SELECT COUNT(*)
FROM players;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0         5

In [5]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football1.db")

player=pd.read_csv("week10.csv")

# CSV 데이터를 SQLite의 player 테이블로 저장
player.to_sql(
    "player",
    conn,
    if_exists="replace",
    index=False
)

query = """
SELECT COUNT(*)
FROM player;
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0        20

In [15]:
query = """
SELECT team, sum(goals), sum(assists)
FROM player
GROUP BY team;
"""

pd.read_sql_query(query, conn)

  team  sum(goals)  sum(assists)
0  리버풀          56            39
1  맨시티          53            45
2   맨유          46            35
3  토트넘          43            37

In [16]:
#1
query = """
SELECT team, count(player)
FROM player
GROUP BY team;
"""

pd.read_sql_query(query, conn)

  team  count(player)
0  리버풀              5
1  맨시티              5
2   맨유              5
3  토트넘              5

In [17]:
#2
query = """
SELECT team, sum(goals)
FROM player
GROUP BY team;
"""

pd.read_sql_query(query, conn)

  team  sum(goals)
0  리버풀          56
1  맨시티          53
2   맨유          46
3  토트넘          43

In [18]:
#3
query = """
SELECT team, sum(assists)
FROM player
GROUP BY team;
"""

pd.read_sql_query(query, conn)

  team  sum(assists)
0  리버풀            39
1  맨시티            45
2   맨유            35
3  토트넘            37

In [19]:
#4
query = """
SELECT team, avg(goals)
FROM player
GROUP BY team;
"""

pd.read_sql_query(query, conn)

  team  avg(goals)
0  리버풀        11.2
1  맨시티        10.6
2   맨유         9.2
3  토트넘         8.6

In [20]:
#5
query = """
SELECT team, max(goals)
FROM player
GROUP BY team;
"""

pd.read_sql_query(query, conn)

  team  max(goals)
0  리버풀          21
1  맨시티          17
2   맨유          16
3  토트넘          15

In [21]:
#6
query = """
SELECT position, count(player)
FROM player
GROUP BY position;
"""

pd.read_sql_query(query, conn)

  position  count(player)
0       DF              4
1       FW              8
2       MF              8

In [22]:
#7
query = """
SELECT position, avg(assists)
FROM player
GROUP BY position;
"""

pd.read_sql_query(query, conn)

  position  avg(assists)
0       DF         2.000
1       FW         7.875
2       MF        10.625

In [23]:
#8
query = """
SELECT team, avg(passes)
FROM player
GROUP BY team
ORDER BY avg(passes) desc
"""

pd.read_sql_query(query, conn)

  team  avg(passes)
0  맨시티       1670.0
1  리버풀       1616.0
2   맨유       1436.0
3  토트넘       1388.0

In [24]:
#9
query = """
SELECT team, sum(goals)
FROM player
WHERE goals>=5
GROUP BY team
"""

pd.read_sql_query(query, conn)

  team  sum(goals)
0  리버풀          52
1  맨시티          53
2   맨유          40
3  토트넘          40

In [25]:
#10
query = """
SELECT team, sum(goals), sum(assists)
FROM player
GROUP BY team
ORDER BY sum(goals) desc
"""

pd.read_sql_query(query, conn)

  team  sum(goals)  sum(assists)
0  리버풀          56            39
1  맨시티          53            45
2   맨유          46            35
3  토트넘          43            37

In [1]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football1.db")

player=pd.read_csv("week10.csv")

query = """
SELECT team, sum(goals), sum(assists)
FROM player
GROUP BY team
ORDER BY sum(goals) desc
"""

pd.read_sql_query(query, conn)

  team  sum(goals)  sum(assists)
0  리버풀          56            39
1  맨시티          53            45
2   맨유          46            35
3  토트넘          43            37

In [2]:
query = """
SELECT team, SUM(goals)
FROM player
GROUP BY team
HAVING SUM(goals) >= 50;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  리버풀          56
1  맨시티          53

In [3]:
query = """
SELECT team, SUM(goals)
FROM player
WHERE goals >= 10
GROUP BY team;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  리버풀          45
1  맨시티          40
2   맨유          40
3  토트넘          27

In [4]:
query = """
SELECT team, SUM(goals)
FROM player
GROUP BY team
HAVING SUM(goals) >= 40;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  리버풀          56
1  맨시티          53
2   맨유          46
3  토트넘          43

In [5]:
query = """
SELECT team, SUM(goals)
FROM player
WHERE goals >= 5
GROUP BY team
HAVING SUM(goals) >= 30;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  리버풀          52
1  맨시티          53
2   맨유          40
3  토트넘          40

In [6]:
query = """
SELECT team, COUNT(*)
FROM player
GROUP BY team
HAVING COUNT(*) >= 5;
"""
pd.read_sql_query(query, conn)

  team  COUNT(*)
0  리버풀         5
1  맨시티         5
2   맨유         5
3  토트넘         5

In [7]:
query = """
SELECT team, AVG(goals)
FROM player
GROUP BY team
HAVING AVG(goals) >= 8;
"""
pd.read_sql_query(query, conn)

  team  AVG(goals)
0  리버풀        11.2
1  맨시티        10.6
2   맨유         9.2
3  토트넘         8.6

In [8]:
query = """
SELECT team, MAX(goals)
FROM player
GROUP BY team
HAVING MAX(goals) >= 15;
"""
pd.read_sql_query(query, conn)

  team  MAX(goals)
0  리버풀          21
1  맨시티          17
2   맨유          16
3  토트넘          15

In [9]:
query = """
SELECT team, SUM(assists)
FROM player
GROUP BY team
HAVING SUM(assists) >= 40;
"""
pd.read_sql_query(query, conn)

  team  SUM(assists)
0  맨시티            45

In [10]:
#1
query = """
SELECT team, SUM(goals)
FROM player
GROUP BY team
HAVING SUM(goals) >= 40;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  리버풀          56
1  맨시티          53
2   맨유          46
3  토트넘          43

In [11]:
#2
query = """
SELECT team, AVG(goals)
FROM player
GROUP BY team
HAVING AVG(goals) >= 8;
"""
pd.read_sql_query(query, conn)

  team  AVG(goals)
0  리버풀        11.2
1  맨시티        10.6
2   맨유         9.2
3  토트넘         8.6

In [12]:
#3
query = """
SELECT team, SUM(assists)
FROM player
GROUP BY team
HAVING SUM(assists) >= 35;
"""
pd.read_sql_query(query, conn)

  team  SUM(assists)
0  리버풀            39
1  맨시티            45
2   맨유            35
3  토트넘            37

In [16]:
#4
query = """
SELECT position, COUNT(player)
FROM player
GROUP BY position
HAVING COUNT(player) >= 5;
"""
pd.read_sql_query(query, conn)

  position  COUNT(player)
0       FW              8
1       MF              8

In [15]:
#5
query = """
SELECT team, MAX(goals)
FROM player
GROUP BY team
HAVING MAX(goals)>=15;
"""
pd.read_sql_query(query, conn)

  team  MAX(goals)
0  리버풀          21
1  맨시티          17
2   맨유          16
3  토트넘          15

In [17]:
#6
query = """
SELECT team, AVG(passes)
FROM player
GROUP BY team
HAVING AVG(passes)>=1500;
"""
pd.read_sql_query(query, conn)

  team  AVG(passes)
0  리버풀       1616.0
1  맨시티       1670.0

In [18]:
#7
query = """
SELECT position, AVG(assists)
FROM player
GROUP BY position
HAVING AVG(assists)>=7;
"""
pd.read_sql_query(query, conn)

  position  AVG(assists)
0       FW         7.875
1       MF        10.625

In [19]:
#8
query = """
SELECT team, SUM(goals)
FROM player
WHERE goals>=5
GROUP BY team
HAVING SUM(goals)>=30;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  리버풀          52
1  맨시티          53
2   맨유          40
3  토트넘          40

In [22]:
#9
query = """
SELECT team, AVG(assists)
FROM player
WHERE position="MF"
GROUP BY team
HAVING AVG(assists)>=8;
"""
pd.read_sql_query(query, conn)

  team  AVG(assists)
0  리버풀          12.0
1  맨시티          11.0
2   맨유          10.0
3  토트넘           9.5

In [24]:
#10
query = """
SELECT team, SUM(goals)
FROM player
WHERE goals>=5
GROUP BY team
HAVING SUM(goals)>=30
ORDER BY SUM(goals) desc;
"""
pd.read_sql_query(query, conn)

  team  SUM(goals)
0  맨시티          53
1  리버풀          52
2  토트넘          40
3   맨유          40

In [1]:
#1
import sqlite3
import pandas as pd

conn=sqlite3.connect("football1.db")

player=pd.read_csv("week10.csv")

query = """
SELECT team, sum(goals), sum(assists)
FROM player
GROUP BY team
ORDER BY sum(goals) desc
"""

pd.read_sql_query(query, conn)

  team  sum(goals)  sum(assists)
0  리버풀          56            39
1  맨시티          53            45
2   맨유          46            35
3  토트넘          43            37

In [2]:
#1
query = """
SELECT team, sum(shots)
FROM player
GROUP BY team
ORDER BY sum(shots) desc
"""

pd.read_sql_query(query, conn)

  team  sum(shots)
0  리버풀         301
1  맨시티         296
2   맨유         262
3  토트넘         255

In [3]:
#2
query = """
SELECT position, avg(passes)
FROM player
GROUP BY position
ORDER BY avg(passes) desc
"""

pd.read_sql_query(query, conn)

  position  avg(passes)
0       DF       2102.5
1       MF       1797.5
2       FW        970.0

In [5]:
#3
query = """
SELECT team, sum(goals), sum(assists)
FROM player
GROUP BY team
ORDER BY sum(goals) desc
"""

pd.read_sql_query(query, conn)

  team  sum(goals)  sum(assists)
0  리버풀          56            39
1  맨시티          53            45
2   맨유          46            35
3  토트넘          43            37

In [6]:
#4
query = """
SELECT team, avg(shots)
FROM player
GROUP BY team
ORDER BY avg(shots) desc
"""

pd.read_sql_query(query, conn)

  team  avg(shots)
0  리버풀        60.2
1  맨시티        59.2
2   맨유        52.4
3  토트넘        51.0

In [7]:
#5
query = """
SELECT position, avg(tackles)
FROM player
GROUP BY position
ORDER BY avg(tackles) desc
"""

pd.read_sql_query(query, conn)

  position  avg(tackles)
0       DF         77.25
1       MF         47.75
2       FW         19.25

In [9]:
#6
query = """
SELECT team, position, avg(passes)
FROM player
WHERE position="MF"
GROUP BY team
ORDER BY avg(passes) desc
"""

pd.read_sql_query(query, conn)

  team position  avg(passes)
0  리버풀       MF       1960.0
1  맨시티       MF       1925.0
2   맨유       MF       1760.0
3  토트넘       MF       1545.0

In [10]:
#7
query = """
SELECT team, sum(goals)
FROM player
WHERE goals>=10
GROUP BY team
"""

pd.read_sql_query(query, conn)

  team  sum(goals)
0  리버풀          45
1  맨시티          40
2   맨유          40
3  토트넘          27

In [11]:
#8
query = """
SELECT team, sum(shots)
FROM player
GROUP BY team
HAVING sum(shots)>=200
ORDER BY sum(shots) desc
"""

pd.read_sql_query(query, conn)

  team  sum(shots)
0  리버풀         301
1  맨시티         296
2   맨유         262
3  토트넘         255

In [12]:
#9
query = """
SELECT team, sum(goals), sum(assists)
FROM player
GROUP BY team
ORDER BY sum(goals) desc
"""

pd.read_sql_query(query, conn)

  team  sum(goals)  sum(assists)
0  리버풀          56            39
1  맨시티          53            45
2   맨유          46            35
3  토트넘          43            37

In [14]:
#10
query = """
SELECT player, goals, assists, goals+assists
FROM player
ORDER BY goals+assists desc
LIMIT 5
"""

pd.read_sql_query(query, conn)

            player  goals  assists  goals+assists
0   Alexander Isak     21        6             27
1  Bruno Fernandes     11       14             25
2    Florian Wirtz     10       15             25
3  Antoine Semenyo     17        8             25
4       Phil Foden     13       12             25

In [18]:
#1. 팀별 공격 생산성 비교
query = """
SELECT team, SUM(goals), SUM(assists), SUM(goals+assists)
FROM player
GROUP BY team
ORDER BY SUM(goals+assists) DESC;
"""

pd.read_sql_query(query, conn)

#위 결과표에서 리버폴은 4팀중 가장많은 골수를 기록하고 있다.
#맨시티는 4팀중 가장많은 어시스트수를 기록하고 있다.
#총득점수와 어시스트수는 맨시티가 98개로 4팀중 가장 높은 수치를 기록하고 있다.
#다만 골과 어시스트만으로 팀의 전체 공격력을 평가하기에는 슈팅 수, 출전시간, 기회 창출 등의 요소가 반영되지 않았다는 한계가 있다.

  team  SUM(goals)  SUM(assists)  SUM(goals+assists)
0  맨시티          53            45                  98
1  리버풀          56            39                  95
2   맨유          46            35                  81
3  토트넘          43            37                  80

In [19]:
#2. 팀별 슈팅 생산량 비교
query = """
SELECT team, SUM(shots)
FROM player
GROUP BY team
ORDER BY SUM(shots) DESC;
"""

pd.read_sql_query(query, conn)

#위 결과표에서 리버풀은 301개로 가장많은 슈팅수를 기록하고있다.
#반면 토트넘은 255개로 4개팀중 가장적은 슈팅수를 기록하고있다.
#하지만 위 결과표만으로 각팀의 슈팅 효율성이 좋았는지에 대해서는 정확하게 알 수가 없다.

  team  SUM(shots)
0  리버풀         301
1  맨시티         296
2   맨유         262
3  토트넘         255

In [22]:
#3. 팀별 평균 패스 관여도 비교
query = """
SELECT team, AVG(passes)
FROM player
GROUP BY team
ORDER BY AVG(passes) DESC;
"""

pd.read_sql_query(query, conn)

#위 결과표에서 맨시티는 평균 패스수가 1670개로 4개팀중 가장많은 평균 패스수를 기록하고 있다
#토트넘은 평균 패스수가 1388개로 4개팀중 가장적은 평균 패스수를 기록하고 있다.
#하지만 위 결과표를 바탕으로 각 팀의 패스 효율성이 높았는지는 판단할 수가 없다.
#맨시티와 토트넘의 선수당 평균 패스 수 차이는 282개로 나타났지만, 이 차이가 실제 볼 점유나 패스 효율의 차이를 의미하는지는 추가 지표가 필요하다.

  team  AVG(passes)
0  맨시티       1670.0
1  리버풀       1616.0
2   맨유       1436.0
3  토트넘       1388.0

In [25]:
#4. 포지션별 수비 관여도 비교
query = """
SELECT position, AVG(tackles), AVG(interceptions)
FROM player
GROUP BY position;
"""

pd.read_sql_query(query, conn)

#위 결과표에서 수비수들은 가장많은 평균 태클수와 평균 인터셉트수를 기록하고 있다.
#공격수들은 다른 포지션대비 적은 태클수와 적은 인터셉트수를 기록하고 있다.
#하지만 위 결과표를 바탕으로 각 포지션의 수비 효율성이 높았는지에 대해서는 판단할 수가 없다.

  position  AVG(tackles)  AVG(interceptions)
0       DF         77.25              51.000
1       FW         19.25               6.875
2       MF         47.75              25.250

In [27]:
#5. 팀별 최고 득점자 기록 비교
query = """
SELECT team, player, MAX(goals)
FROM player
GROUP BY team
ORDER BY MAX(goals) DESC;
"""

pd.read_sql_query(query, conn)

#위 결과표에서 리버풀소속 이삭선수가 21골로 가장높은 골을 기록하고있다.
#반면 솔랑케선수는 15개 골로 위 결과표에서 가장 낮은 순위에 위치해 있다.
#하지만 위결과표를 바탕으로 각 선수의 득점 효율성에 대해서는 판단할 수가 없다.

  team           player  MAX(goals)
0  리버풀   Alexander Isak          21
1  맨시티  Antoine Semenyo          17
2   맨유   Benjamin Sesko          16
3  토트넘  Dominic Solanke          15