In [6]:
import sqlite3
import pandas as pd

conn=sqlite3.connect("football.db")

players=pd.read_csv("player.csv")


players.to_sql(
    "players",
    conn,
    if_exists="replace",
    index=False
)

5

In [11]:
query = """
SELECT * 
FROM players
LIMIT 5;
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    김민재      2        1    뮌헨
4    조규성      6        2  미트윌란

In [8]:
query = """
SELECT *
FROM players;
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    김민재      2        1    뮌헨
4    조규성      6        2  미트윌란

In [9]:
query = """
SELECT player, team
FROM players;
"""

pd.read_sql_query(query, conn)

  player  team
0    손흥민   토트넘
1    이강인    파리
2    황희찬   울브즈
3    김민재    뮌헨
4    조규성  미트윌란

In [11]:
query = """
SELECT DISTINCT goals
FROM players;
"""

pd.read_sql_query(query, conn)

   goals
0     15
1      8
2     10
3      2
4      6

In [12]:
query = """
SELECT DISTINCT assists
FROM players;
"""

pd.read_sql_query(query, conn)

   assists
0        9
1        6
2        3
3        1
4        2

In [13]:
query = """
SELECT *
FROM players;
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    김민재      2        1    뮌헨
4    조규성      6        2  미트윌란

In [16]:
query = """
SELECT *
FROM players
WHERE goals>=5;
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    조규성      6        2  미트윌란

In [17]:
query = """
SELECT *
FROM players
WHERE goals>=5
AND assists>=2;
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    조규성      6        2  미트윌란

In [18]:
query = """
SELECT *
FROM players
WHERE goals>=5
OR assists>=2;
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    조규성      6        2  미트윌란

In [3]:
#1
import sqlite3
import pandas as pd

conn=sqlite3.connect("football.db")

query = """
SELECT *
FROM players
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    김민재      2        1    뮌헨
4    조규성      6        2  미트윌란

In [5]:
#2
query = """
SELECT player
FROM players
"""

pd.read_sql_query(query, conn)

  player
0    손흥민
1    이강인
2    황희찬
3    김민재
4    조규성

In [6]:
#3
query = """
SELECT player, goals
FROM players
"""

pd.read_sql_query(query, conn)

  player  goals
0    손흥민     15
1    이강인      8
2    황희찬     10
3    김민재      2
4    조규성      6

In [7]:
#4
query = """
SELECT player, goals, assists
FROM players
"""

pd.read_sql_query(query, conn)

  player  goals  assists
0    손흥민     15        9
1    이강인      8        6
2    황희찬     10        3
3    김민재      2        1
4    조규성      6        2

In [8]:
#5
query = """
SELECT player, team
FROM players
"""

pd.read_sql_query(query, conn)

  player  team
0    손흥민   토트넘
1    이강인    파리
2    황희찬   울브즈
3    김민재    뮌헨
4    조규성  미트윌란

In [10]:
#6
query = """
SELECT DISTINCT team
FROM players
"""

pd.read_sql_query(query, conn)

   team
0   토트넘
1    파리
2   울브즈
3    뮌헨
4  미트윌란

In [12]:
#7
query = """
SELECT DISTINCT goals
FROM players
"""

pd.read_sql_query(query, conn)

   goals
0     15
1      8
2     10
3      2
4      6

In [13]:
#8
query = """
SELECT DISTINCT assists
FROM players
"""

pd.read_sql_query(query, conn)

   assists
0        9
1        6
2        3
3        1
4        2

In [14]:
#9
query = """
SELECT DISTINCT team, goals
FROM players
"""

pd.read_sql_query(query, conn)

   team  goals
0   토트넘     15
1    파리      8
2   울브즈     10
3    뮌헨      2
4  미트윌란      6

In [15]:
#10
query = """
SELECT player, goals, assists, team
FROM players
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    김민재      2        1    뮌헨
4    조규성      6        2  미트윌란

In [16]:
#1
query = """
SELECT *
FROM players
WHERE goals>=5
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    이강인      8        6    파리
2    황희찬     10        3   울브즈
3    조규성      6        2  미트윌란

In [19]:
#2
query = """
SELECT *
FROM players
WHERE assists>=3
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘
1    이강인      8        6   파리
2    황희찬     10        3  울브즈

In [21]:
#3
query = """
SELECT player, goals
FROM players
WHERE goals>=5
"""

pd.read_sql_query(query, conn)

  player  goals
0    손흥민     15
1    이강인      8
2    황희찬     10
3    조규성      6

In [22]:
#4
query = """
SELECT *
FROM players
WHERE goals>=5 and assists>=3
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘
1    이강인      8        6   파리
2    황희찬     10        3  울브즈

In [23]:
#5
query = """
SELECT player, goals, assists
FROM players
WHERE goals>=10 and assists>=5
"""

pd.read_sql_query(query, conn)

  player  goals  assists
0    손흥민     15        9

In [26]:
#6
query = """
SELECT *
FROM players
WHERE goals>=10 OR assists>=5
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘
1    이강인      8        6   파리
2    황희찬     10        3  울브즈

In [25]:
#7
query = """
SELECT *
FROM players
WHERE goals>=10 and team="토트넘"
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘

In [27]:
#8
query = """
SELECT *
FROM players
WHERE assists>=5 and team="토트넘"
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘

In [28]:
#9
query = """
SELECT player, goals, assists, team
FROM players
WHERE assists>=7 or goals>=10
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘
1    황희찬     10        3  울브즈

In [29]:
#10
query = """
SELECT player, goals, assists, team
FROM players
WHERE goals>=10 and assists>=5 and team="토트넘"
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘

In [33]:
#1
query = """
SELECT *
FROM players
ORDER BY goals
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    김민재      2        1    뮌헨
1    조규성      6        2  미트윌란
2    이강인      8        6    파리
3    황희찬     10        3   울브즈
4    손흥민     15        9   토트넘

In [35]:
#2
query = """
SELECT player, goals
FROM players
ORDER BY goals desc
"""

pd.read_sql_query(query, conn)

  player  goals
0    손흥민     15
1    황희찬     10
2    이강인      8
3    조규성      6
4    김민재      2

In [36]:
#3
query = """
SELECT player, assists
FROM players
ORDER BY assists
"""

pd.read_sql_query(query, conn)

  player  assists
0    김민재        1
1    조규성        2
2    황희찬        3
3    이강인        6
4    손흥민        9

In [38]:
#4
query = """
SELECT player, goals
FROM players
ORDER BY goals desc
LIMIT 5
"""

pd.read_sql_query(query, conn)

  player  goals
0    손흥민     15
1    황희찬     10
2    이강인      8
3    조규성      6
4    김민재      2

In [39]:
#5
query = """
SELECT player, assists
FROM players
ORDER BY assists desc
LIMIT 3
"""

pd.read_sql_query(query, conn)

  player  assists
0    손흥민        9
1    이강인        6
2    황희찬        3

In [42]:
#6
query = """
SELECT *
FROM players
WHERE goals>=5
ORDER BY goals desc
"""

pd.read_sql_query(query, conn)

  player  goals  assists  team
0    손흥민     15        9   토트넘
1    황희찬     10        3   울브즈
2    이강인      8        6    파리
3    조규성      6        2  미트윌란

In [44]:
#7
query = """
SELECT player, goals, assists
FROM players
WHERE team="토트넘"
ORDER BY goals desc
LIMIT 5
"""

pd.read_sql_query(query, conn)

  player  goals  assists
0    손흥민     15        9

In [45]:
#8
query = """
SELECT player, goals, assists
FROM players
WHERE assists>=3 and goals>=5
ORDER BY assists desc
"""

pd.read_sql_query(query, conn)

  player  goals  assists
0    손흥민     15        9
1    이강인      8        6
2    황희찬     10        3

In [48]:
#9
query = """
SELECT player, goals, assists, team
FROM players
WHERE assists>=7 or goals>=10
ORDER BY goals desc
LIMIT 5
"""

pd.read_sql_query(query, conn)

  player  goals  assists team
0    손흥민     15        9  토트넘
1    황희찬     10        3  울브즈

In [49]:
#10
query = """
SELECT player, goals, assists
FROM players
WHERE team="토트넘" and goals>=5
ORDER BY goals desc
LIMIT 3
"""

pd.read_sql_query(query, conn)

  player  goals  assists
0    손흥민     15        9